definitions:
  config:
    /hst:hst/hst:configurations/hippoaddoncrispdemo/hst:pages/productspage:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        hst:componentclassname: productListComponent
        hst:template: productspage-main
        /container:
          jcr:primaryType: hst:containercomponentreference
          hst:referencecomponent: productspage/main
